name: Wankel
markdown: redcarpet
highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
assets:
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
port: 8000
